[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = False
logfile = /var/log/odoo/odoo.log
log_level = info
admin_passwd = $pbkdf2-sha512$600000$h/Dem7PWupcyxpgzpnRuTQ$dbUYwP26bHlk5JrVawQJP6sHkL3dUu.iqSgb9h6i8KdzWgz0NWTwTsZYohyQ7DnnopVJqFLOPlye.knBnM0FsA

